document.addEventListener("DOMContentLoaded",()=>{
const key="aureliaAccount";
const defaultAccount={firstName:"",lastName:"",email:"",phone:"",country:"",preference:"Quiet garden-facing room",created:false};
const get=()=>JSON.parse(localStorage.getItem(key)||"null")||{...defaultAccount};
const save=a=>localStorage.setItem(key,JSON.stringify(a));
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const status=(id,msg,error=false)=>{const e=document.getElementById(id);if(e){e.textContent=msg;e.classList.toggle("is-error",error)}};
const year=document.querySelector("[data-current-year]");if(year)year.textContent=new Date().getFullYear();

/* Contact */
const cf=document.getElementById("contact-form");if(cf)cf.addEventListener("submit",e=>{e.preventDefault();if(!cf.checkValidity()){cf.reportValidity();return}const messages=JSON.parse(localStorage.getItem("aureliaContactMessages")||"[]");messages.push({name:document.getElementById("contact-name").value,email:document.getElementById("contact-email").value,topic:document.getElementById("contact-topic").value,message:document.getElementById("contact-message").value,createdAt:new Date().toISOString()});localStorage.setItem("aureliaContactMessages",JSON.stringify(messages));cf.reset();status("contact-message-status","Thank you. Our Concierge will be in touch shortly.")});

/* Login */
const lf=document.getElementById("login-form");if(lf)lf.addEventListener("submit",e=>{e.preventDefault();if(!lf.checkValidity()){lf.reportValidity();return}const a=get();const email=document.getElementById("login-email").value.trim();if(!a.created||a.email.toLowerCase()!==email.toLowerCase()){status("login-status","No local Aurelia account matches this email. Create an account first.",true);return}localStorage.setItem("aureliaLoggedIn","true");status("login-status","Welcome back. Redirecting…");setTimeout(()=>location.href="dashboard.html",500)});

/* Sign up */
const sf=document.getElementById("signup-form");if(sf)sf.addEventListener("submit",e=>{e.preventDefault();if(!sf.checkValidity()){sf.reportValidity();return}const p=document.getElementById("signup-password").value,c=document.getElementById("signup-confirm").value;if(p!==c){status("signup-status","Passwords do not match.",true);return}const a={firstName:document.getElementById("signup-first").value.trim(),lastName:document.getElementById("signup-last").value.trim(),email:document.getElementById("signup-email").value.trim(),phone:"",country:"",preference:"Quiet garden-facing room",created:true};save(a);localStorage.setItem("aureliaLoggedIn","true");status("signup-status","Your account is ready. Redirecting…");setTimeout(()=>location.href="dashboard.html",500)});

/* Profile */
const pf=document.getElementById("profile-form");if(pf){const a=get();["first","last"].forEach(x=>document.getElementById(`profile-${x}`).value=a[x==="first"?"firstName":"lastName"]||"");document.getElementById("profile-email-input").value=a.email||"";document.getElementById("profile-phone").value=a.phone||"";document.getElementById("profile-country").value=a.country||"";document.getElementById("profile-preference").value=a.preference||"Quiet garden-facing room";document.getElementById("profile-name").textContent=`${a.firstName||"Aurelia"} ${a.lastName||"Guest"}`;document.getElementById("profile-email").textContent=a.email||"Guest account";document.getElementById("profile-avatar").textContent=(a.firstName||"A").charAt(0).toUpperCase();pf.addEventListener("submit",e=>{e.preventDefault();if(!pf.checkValidity()){pf.reportValidity();return}const n={...get(),firstName:document.getElementById("profile-first").value.trim(),lastName:document.getElementById("profile-last").value.trim(),email:document.getElementById("profile-email-input").value.trim(),phone:document.getElementById("profile-phone").value.trim(),country:document.getElementById("profile-country").value.trim(),preference:document.getElementById("profile-preference").value};n.created=true;save(n);document.getElementById("profile-name").textContent=`${n.firstName} ${n.lastName}`;document.getElementById("profile-email").textContent=n.email;document.getElementById("profile-avatar").textContent=n.firstName.charAt(0).toUpperCase();status("profile-status","Your profile has been saved.")})}

/* Dashboard */
const dn=document.getElementById("dashboard-name");if(dn){const a=get();dn.textContent=`${a.firstName||"Guest"}.`}

/* Favorites */
const fl=document.getElementById("favorites-list");if(fl){let fav=JSON.parse(localStorage.getItem("aureliaFavorites")||"[]");const empty=document.getElementById("favorites-empty");const render=()=>{if(!fav.length){fl.innerHTML="";empty.hidden=false;return}empty.hidden=true;fl.innerHTML=fav.map((x,i)=>`<article class="favorite-card account-panel"><span>${esc(x.type||"Saved")}</span><h3>${esc(x.name)}</h3><p>${esc(x.description||"Aurelia discovery saved to your favorites.")}</p><button class="btn btn-secondary btn-sm favorite-remove" data-remove="${i}" type="button">Remove</button></article>`).join("");fl.querySelectorAll("[data-remove]").forEach(b=>b.addEventListener("click",()=>{fav.splice(Number(b.dataset.remove),1);localStorage.setItem("aureliaFavorites",JSON.stringify(fav));render()}))};render()}

/* Search history */
const hl=document.getElementById("history-list");if(hl){let hist=JSON.parse(localStorage.getItem("aureliaSearchHistory")||"[]");const empty=document.getElementById("history-empty"),clear=document.getElementById("clear-history");const render=()=>{if(!hist.length){hl.innerHTML="";empty.hidden=false;clear.hidden=true;return}empty.hidden=true;clear.hidden=false;hl.innerHTML=hist.slice(0,20).map((x,i)=>`<article class="history-item"><div><strong>${esc(x.label||"Stay search")}</strong><span>${esc(x.details||"Aurelia search")} · ${x.createdAt?new Date(x.createdAt).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"}):""}</span></div><a href="booking.html">Search again →</a></article>`).join("")};clear.addEventListener("click",()=>{hist=[];localStorage.setItem("aureliaSearchHistory","[]");render()});render()}

/* Settings */
const st=document.getElementById("settings-form");if(st){const s=JSON.parse(localStorage.getItem("aureliaSettings")||"{}");document.getElementById("setting-reservations").checked=s.reservations!==false;document.getElementById("setting-concierge").checked=!!s.concierge;document.getElementById("setting-offers").checked=!!s.offers;document.getElementById("setting-motion").checked=!!s.motion;st.addEventListener("submit",e=>{e.preventDefault();const v={reservations:document.getElementById("setting-reservations").checked,concierge:document.getElementById("setting-concierge").checked,offers:document.getElementById("setting-offers").checked,motion:document.getElementById("setting-motion").checked};localStorage.setItem("aureliaSettings",JSON.stringify(v));document.documentElement.classList.toggle("reduced-motion",v.motion);status("settings-status","Preferences saved.")})}
const lo=document.getElementById("logout-button");if(lo)lo.addEventListener("click",()=>{localStorage.setItem("aureliaLoggedIn","false");location.href="index.html"});
const ca=document.getElementById("clear-account-button");if(ca)ca.addEventListener("click",()=>{if(confirm("Clear local Aurelia account data?")){localStorage.removeItem("aureliaAccount");localStorage.removeItem("aureliaSettings");localStorage.setItem("aureliaLoggedIn","false");location.href="index.html"}});

const fp=document.getElementById("forgot-password");if(fp)fp.addEventListener("click",e=>{e.preventDefault();status("login-status","For this prototype, password recovery is not connected to a server. Create a new local account or contact Concierge.")});
});
