document.addEventListener("DOMContentLoaded",()=>{const DATA=[
{type:"room",label:"Suite",name:"Garden Suite",price:"$480",image:"assets/images/room-garden-suite.png",description:"A serene suite opening onto private gardens, with generous living space and soft natural light.",meta:["72 m²","2 Guests","King Bed","Private Garden"],href:"room-details.html?room=garden",keywords:"garden suite room private garden quiet natural light king bed"},
{type:"room",label:"Room",name:"Deluxe Room",price:"$320",image:"assets/images/room-deluxe.png",description:"An elegant retreat balancing refined comfort, warm textures, and views across the estate.",meta:["42 m²","2 Guests","King Bed","Estate View"],href:"room-details.html?room=deluxe",keywords:"deluxe room estate view king bed refined comfort"},
{type:"room",label:"Room",name:"Terrace Room",price:"$390",image:"assets/images/room-terrace.png",description:"A light-filled room with a private terrace, designed for slow mornings and quiet evenings.",meta:["50 m²","2 Guests","King Bed","Private Terrace"],href:"room-details.html?room=terrace",keywords:"terrace room private terrace outdoor slow mornings"},
{type:"dining",label:"Dining",name:"Aurelia Dining",price:"À la carte",image:"assets/images/dining-aurelia.png",description:"Seasonal dining shaped by local ingredients, warm interiors, and an unhurried evening rhythm.",meta:["Dinner","Seasonal","Private dining"],href:"dining.html",keywords:"dining restaurant dinner seasonal food private dining"},
{type:"experience",label:"Experience",name:"Wellness & Rituals",price:"By arrangement",image:"assets/images/experience-wellness.png",description:"Quiet rituals designed to restore the body and mind in the natural surroundings of the estate.",meta:["Wellness","Private","Concierge"],href:"experiences.html",keywords:"wellness spa experience ritual massage quiet"},
{type:"experience",label:"Experience",name:"Estate Experiences",price:"By arrangement",image:"assets/images/experience-estate.png",description:"Thoughtful ways to discover the landscape, culture, and slower rhythm around Aurelia.",meta:["Private","Outdoor","Concierge"],href:"experiences.html",keywords:"estate experience outdoor culture nature private concierge"}];

const form=document.getElementById("search-results-form"),qInput=document.getElementById("results-query"),typeInput=document.getElementById("results-type"),grid=document.getElementById("results-grid"),empty=document.getElementById("results-empty"),title=document.getElementById("results-title"),count=document.getElementById("results-count"),showAll=document.getElementById("show-all");
if(!form)return;
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const params=new URLSearchParams(location.search);qInput.value=params.get("q")||"";typeInput.value=["all","room","dining","experience"].includes(params.get("type"))?params.get("type"):"all";

function saveHistory(){const q=qInput.value.trim(),type=typeInput.value;if(!q&&type==="all")return;const h=JSON.parse(localStorage.getItem("aureliaSearchHistory")||"[]");const label=q||({room:"Rooms & Suites",dining:"Dining",experience:"Experiences"}[type]||"Aurelia");const resultCount=filter().length;const item={label,details:`${resultCount} ${resultCount===1?"result":"results"}`,query:q,type,createdAt:new Date().toISOString()};localStorage.setItem("aureliaSearchHistory",JSON.stringify([item,...h.filter(x=>!(x.query===q&&x.type===type))].slice(0,20)))}
function filter(){const q=qInput.value.trim().toLowerCase(),type=typeInput.value;return DATA.filter(x=>(type==="all"||x.type===type)&&(!q||`${x.name} ${x.description} ${x.keywords} ${x.meta.join(" ")}`.toLowerCase().includes(q)))}
function render(){const r=filter(),q=qInput.value.trim(),t=typeInput.value;title.textContent=q?`Results for “${q}”`:(t==="room"?"Rooms & Suites":t==="dining"?"Dining":t==="experience"?"Experiences":"Everything at Aurelia");count.textContent=`${r.length} ${r.length===1?"result":"results"}`;if(!r.length){grid.innerHTML="";empty.hidden=false;return}empty.hidden=true;grid.innerHTML=r.map(x=>`<article class="result-card"><a class="result-media" href="${esc(x.href)}"><img src="${esc(x.image)}" alt="${esc(x.name)}" loading="lazy"><span class="result-type">${esc(x.label)}</span></a><div class="result-body"><div class="result-top"><h3>${esc(x.name)}</h3><div class="result-price">${esc(x.price)}</div></div><p class="result-description">${esc(x.description)}</p><div class="result-meta">${x.meta.map(m=>`<span>${esc(m)}</span>`).join("")}</div><a class="result-link" href="${esc(x.href)}">Explore <span>→</span></a></div></article>`).join("")}
function updateURL(){const p=new URLSearchParams(),q=qInput.value.trim(),t=typeInput.value;if(q)p.set("q",q);if(t!=="all")p.set("type",t);history.replaceState({}, "",p.toString()?`search.html?${p}`:"search.html")}
form.addEventListener("submit",e=>{e.preventDefault();updateURL();saveHistory();render()});
typeInput.addEventListener("change",()=>{updateURL();render()});
showAll.addEventListener("click",()=>{qInput.value="";typeInput.value="all";updateURL();render()});
document.querySelectorAll(".search-form").forEach(f=>f.addEventListener("submit",e=>{const input=f.querySelector("#nav-search");if(!input)return;e.preventDefault();const q=input.value.trim();location.href=q?`search.html?q=${encodeURIComponent(q)}`:"search.html"}));
const year=document.querySelector("[data-current-year]");if(year)year.textContent=new Date().getFullYear();render();
});